### ISSUE TITLE
mixup_data

### ISSUE THREAD

**Issue by jiantenggei** [LetheSec/Fer2013-Recognition-Pytorch#2]
hi ! i want know the theory of mixup_data function in utils.py
 你好 我想问一下 mixup_data 的原理是什么。

**Comment by LetheSec** [comment]
是用到了mixup的技术，来自这篇文章：[mixup: Beyond Empirical Risk Minimization
](https://arxiv.org/abs/1710.09412)

**Comment by jiantenggei** [comment]
好的 我了解一下 十分感谢你的回复





------------------ Original ------------------
From: Lethe ***@***.***&gt;
Date: Mon,May 9,2022 3:56 PM
To: LetheSec/Fer2013-Facial-Emotion-Recognition-Pytorch ***@***.***&gt;
Cc: Jian Tengfei ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [LetheSec/Fer2013-Facial-Emotion-Recognition-Pytorch] mixup_data(Issue #2)





 
是用到了mixup的技术，来自这篇文章：mixup: Beyond Empirical Risk Minimization
