### ISSUE TITLE
train acc  比  test  acc  低20% 是为什么呢？

### ISSUE THREAD

**Issue by xioapangzi** [LetheSec/Fer2013-Recognition-Pytorch#7]
您好，很感谢您提供的开源代码，我按照您的模板，可以实现您的效果 在FER2013上 test ACC 能到73%+
但是有一个疑问，就是为什么训练的acc，会比测试acc低将近20%。
正常来说应该train acc  略高于 test acc才对。
非常希望您能解答一下！
再次感谢~~

**Comment by LetheSec** [comment]
因为在训练过程中使用了mixup技术

**Comment by xioapangzi** [comment]
非常感谢您的解答，谢谢~~
